### PR TITLE
Two minor changes

### PR DESCRIPTION
**Pull request by njale**
Handles lookup of TadTip.exe in customized and/or localized OS installations
Handles missing taskbar (i.e. kiosk mode)

### CODE REVIEW

**Comment by maximcus** [comment]
@njale , you tested your changes? Device with kiosk mode is working correctly after them?

**Comment by njale** [comment]
They tested your current version with and without kiosk mode. Works fine in normal mode. In kiosk mode the current version crashes on Taskbar.cs line 55 where you throw an exception if you cannot get a handle to the taskbar. I handle that situation and use currentScreenBounds as you suggested. My simulated tests behaves correctly, but my co-workers who do the testing left for the weekend before they tested my latest fix. Although I am very confident it will solve this problem, you are absolutely right. We should do a proper test. They will hopefully test it first thing on Monday (Norwegian time) and I will get back to you with the result.

**Comment by maximcus** [comment]
Yes, thanks for understanding. I am also fairly confident in your solution, but i believe that confidence can lead to errors in production)

**Comment by njale** [comment]
I can confirm that the change fixed the problem with kiosk-mode.

**Comment by maximcus** [comment]
Great!

**Comment by maximcus** [comment]
I tested your changes and found out that code determining TabTip.exe file location was not working correctly. On 64 bit machine it returned "Program Files (x86)" when WPFTabTip library was targeting 32 bit. So i decided to stay with hardcoded path for the time being. Maybe that was the source of your problems with 64 bit machines, that you described previously?

Anyway, i merged everything else, and new NuGet package is already published.

**Comment by njale** [comment]
Pretty silly that API, it determines path based on build model (32 or 64 bit), not the OS it is running on. I can look into it. Hard-coded will fail on many machines, so not a good solution either.

Anyway, this did not cause my problem as I had not implemented it back then. Just noticed later.

**Comment by maximcus** [comment]
Tell me, you are primarily concerned that the disk partition, on which system will be installed will differ from C:\ ? If we will get correct disk partition then after that it will always be "Program Files", or you are thinking that even "Program Files" can be named differently?

**Pull request merged**
