### PR TITLE
Add support for ignoring multiple keyboard devices

### PR DESCRIPTION
**Pull request by wldevries**
PR for #7

### CODE REVIEW

**Comment by maximcus** [comment]
Can you please make a pull request to my 'ignore-multiple-instances' branch (not master). I want to test your changes before merging them to master branch.

**Comment by maximcus** [comment]
In this PR you changed `ListOfHardwareKeyboardsToIgnoreIfSingleInstance` to `IgnoredDevices`, but you have to realize that `ListOfHardwareKeyboardsToIgnoreIfSingleInstance` is part of public API of this library. If I would accept this change as is, it will break existing code of users of WPFTabTip. I recommend that you add new list `IgnoredDevices`, and do not change `ListOfHardwareKeyboardsToIgnoreIfSingleInstance`.

**Comment by wldevries** [comment]
I pushed another commit to reinstate the property. It would have been more convenient if you kept this PR open to let me work on it.

**Comment by maximcus** [comment]
Ok, sorry, i will reopen it

**Pull request merged**
