### PR TITLE
add options to decide whether popup in docked

### PR DESCRIPTION
**Pull request by zzczzc004**

### CODE REVIEW

**Comment by maximcus** [comment]
Hi, can you please make a pull request to PullRequestBranch (not master). I want to test your changes before merging them to master branch.

**Comment by zzczzc004** [comment]
@maximcus OK, I have changed it.

**Comment by maximcus** [comment]
I tested your changes and found that they do not work nicely with my animation, which moves selected visual element into view.
With full screen app you can disable animation, and this will presumably be ok. This is a screencast of a problem with full screen: http://recordit.co/caRlBz9bUp
With non full screen app problem is harder to resolve. This is a screen cast: http://recordit.co/4BAV1xhk3W . It will be better if you try it for yourself, test project (UITest) is part of WPFTabTip solution.
I do not know if you will be able to resolve this issues, and if it is worth your time, but unless they are resolved I will not accept this changes.

**Comment by zzczzc004** [comment]
I am sorry, I can't catch your points. Do you mean the error is that the view don't change back to the original size in your second animation?

**Comment by maximcus** [comment]
@zzczzc004, so much time passed, i do not remember exactly, but from what i see in my links:
1. In fullscreen view moves much higher than it needs (in fullscreen with docked TabTip i think animation is not necessary at all)
2. without fullscreen window moves higher than it needs and it moves back with some jerks.

To understand it you just need to test it.

**Comment by zzczzc004** [comment]
I find why I can't catch your points because I can't reproduce the problem. In my computer, the screencast in full screen is http://recordit.co/Es5AtAHeC4.

**Comment by maximcus** [comment]
@zzczzc004, i think that docked TabTip behaves differently on Win 10 vs Win 8.1. So maybe everything  is ok on Win 10, but as my main use for this project in production is on Win 8.1, i will be able to accept your changes only if they will work nicely on Win 8.1 as well. When my users start to move to Win 10, i will be able to test this project on Win 10, but until then, i cannot do that. So if you will not be able to make docked state of TabTip work nicely on Win 8.1 i suggest you just fork this project, and use your fork, as i do not have plans to add any new functionality to this project, only bug fixes.

**Comment by zzczzc004** [comment]
@maximcus Yes, I got it. My project needn't to be run in Win 8.1. This problem seems to skip now and solve in future if necessary. Thank you for your advice.

**Pull request merged**
