### PR TITLE
Patch for Windows 10 Anniversary Update

### LINKED ISSUE #2: Problems with Windows 10 Anniversary Update
So far I love that you are tackling this problem. I am tinkering around with TabTip and osk since forever. So problem is after update to windows 10 anniversary some things seem to be broken.

1. dotnet 4.6.2 promised to enable focus tracking including toggling soft keyboard, but it doesn't so far. At least not for me.

1.1 [Announcing .NET Framework 4.6.2](https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/)

1.2 [forum about not working really](https://social.msdn.microsoft.com/Forums/vstudio/en-US/540e17a1-8b60-4f67-bd55-c20fb7c07bda/wpf-net-462-windows-10-soft-keyboard-support-not-working-?forum=wpf)

Problem is executing TabTip.exe doesn't actually open the soft keyboard anymore. See [stackoverflow discussion](http://stackoverflow.com/questions/38774139/show-touch-keyboard-tabtip-exe-in-windows-10-anniversary-edition). The proposed solution with EnableDesktopModeAutoInvoke doesn't work for me.

If we are lucky this should get resolved with an update. Until than I don't know how to proceed now.

### PR DESCRIPTION
**Pull request by buffcode**
- fixes #2 
- includes a new option "DockMode"
- automatically triggers the keyboard tray icon
- small refactoring of Open vs OpenUndocked

### CODE REVIEW

**Comment by maximcus** [comment]
I will test everything tomorrow, and if nothing is broken i will merge.
In your case this fix resolved issue #2 , and now everything is working as expected?

**Comment by buffcode** [comment]
Yes it works again now. The only thing I experienced are the following two glitches, but I don't know if they existed before as I cannot test it:

- switching between two TextBoxes will minimize the OSK
- when switching between Docked/Undocked (killing the process after registry update), the OSK will not appear on the first call

**Comment by maximcus** [comment]
no, this is new..
I don't really like this solution, wonder if there is another way around this issue.
And i would like to know what will happen if tray icon is not present? (because you can hide it, and i don't know, maybe it even hidden by default)

**Comment by maximcus** [comment]
Would it be possible for you to give me access to you tablet via TeamViewer tomorrow? I need to at least fix new problems you mentioned. And maybe try and find some other way around this issue.

**Comment by buffcode** [comment]
Sure, I will send you an e-mail with more information. May be I already have an updated version then.

**Comment by maximcus** [comment]
yes, if you could fix it on your own, would be even easier for me)

**Comment by smlacombe** [comment]
Hi, I was wondering if the developpement of this patch has been abandoned or if a solution is currently being developped.

**Comment by maximcus** [comment]
This particular pull request does not resolve the issue. It is a good attempt, but it will only work if soft icon is present in the tray. Otherwise nothing will happen. I hope to find a solution for this problem, but i do not currently have a machine where i can reproduce it. And to be honest this project is not in the top of my priorities right now. But if anybody can resolve this issue, i would be very happy)

**Pull request closed without merging**
